spring:
  application:
    name: cat-service
  datasource:
    url: jdbc:postgresql://localhost:1001/catsharing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  kafka:
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
          json:
#            add:
#              type:
#                headers: false
            type:
              mapping: sdcReq:ru.xplago.common.kafka.models.sale.deal.SaleDealCatRequestModel
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false
            type:
              mapping: sdcRes:ru.xplago.common.kafka.models.sale.deal.SaleDealCatResponseModel
    jaas:
      enabled: true
    properties:
      security:
        protocol: SASL_PLAINTEXT
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";


grpc:
  server:
    port: ${CAT_SERVICE_GRPC_PORT:9091}
  jwt:
    algorithm: HmacSHA256
    secret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
    expiration-sec: 3600
