spring:
  application:
    name: trade-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:1001/catsharing}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81}
  kafka:
    bootstrap-servers:
      - ${KAFKA_URL:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            add:
              type:
                headers: true
            type:
              mapping: saleDeal:ru.xplago.common.kafka.models.sale.deal.SaleDealModel,sdcRes:ru.xplago.common.kafka.models.sale.deal.SaleDealCatResponseModel,sdpRes:ru.xplago.common.kafka.models.sale.deal.SaleDealPaymentResponseModel
            trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
#            add:
#              type:
#                headers: false
            type:
              mapping: saleDeal:ru.xplago.common.kafka.models.sale.deal.SaleDealModel,sdpReq:ru.xplago.common.kafka.models.sale.deal.SaleDealPaymentRequestModel,sdcReq:ru.xplago.common.kafka.models.sale.deal.SaleDealCatRequestModel,sdcRes:ru.xplago.common.kafka.models.sale.deal.SaleDealCatResponseModel,sdpRes:ru.xplago.common.kafka.models.sale.deal.SaleDealPaymentResponseModel
            trusted.packages: "*"
    jaas:
      enabled: true
    properties:
      security:
        protocol: SASL_PLAINTEXT
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME:admin}" password="${KAFKA_PASSWORD:admin-secret}";
    streams:
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: saleDeal:ru.xplago.common.kafka.models.sale.deal.SaleDealModel,sdcRes:ru.xplago.common.kafka.models.sale.deal.SaleDealCatResponseModel,sdpRes:ru.xplago.common.kafka.models.sale.deal.SaleDealPaymentResponseModel


grpc:
  server:
    port: ${GRPC_PORT:9095}
  client:
    catService:
      negotiation-type: PLAINTEXT
      address: ${CAT_SERVICE_URL:localhost:9091}
    paymentService:
      negotiation-type: PLAINTEXT
      address: ${PAYMENT_SERVICE_URL:localhost:9093}

  jwt:
    algorithm: HmacSHA256
    secret: ${JWT_SECRET:357638792F423F4428472B4B6250655368566D597133743677397A2443264629}
    expiration-sec: ${JWT_EXPIRATION:3600}
