name: Cat Sharing deploy
on: push
jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - name: Build gradle project
        run: sudo chmod u+x ./gradlew && ./gradlew clean :auth-service:build :cat-service:build :mail-service:build :payment-service:build :trade-service:build :transaction-service:build
      - name: Docker compose build
        run: docker-compose build
      - name: Docker compose up
        run: docker-compose up