name: Cat Sharing deploy
on: push
jobs:
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Build gradle project
        run: sudo chmod u+x ./gradlew && ./gradlew clean :auth-service:build :cat-service:build :mail-service:build :payment-service:build :trade-service:build :transaction-service:build
      - name: docker-compose
        run: docker compose up -d --build