name: Cat Sharing deploy
on: push
jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Build services images
        run: docker run :auth-service:bootBuildImage
      - name: Docker compose up
        run: docker-compose up