name: Cat Sharing deploy
on: push
jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build services images
        run: gradle :auth-service:bootBuildImage
      - name: Docker compose up
        run: docker-compose up